export {
  backgroundRemovalFailedError,
  fileStorageFailedError,
  fileTooLargeError,
  imageRequiredError,
  imagesRequiredError,
  modelLoadingError,
  modelUnavailableError,
  multipleImagesError,
  noRemovableSubjectError,
  processingFailedError,
  processingQueueFullError,
  tooManyImagesError,
  unsupportedImageTypeError,
  validationError,
} from '../../shared/errors/app-error.js';
